### ISSUE TITLE
Fix CI build

### ISSUE THREAD

**Issue by guigarfr** [globality-corp/flake8-logging-format#42]
[CI build](https://app.circleci.com/pipelines/github/globality-corp/flake8-logging-format/28/workflows/e24a39d0-ceae-4ef7-83c9-d4bc6b761853/jobs/262) publish step is failing because twine requirement is not found.

This makes this project unable to publish any releases.

**Comment by piercefreeman** [comment]
Thanks for the report @guigarfr. We're going to try to fix this today.

**Comment by piercefreeman** [comment]
With https://github.com/globality-corp/flake8-logging-format/releases/tag/0.7.4 we have fixed the release pipeline and pushed a new version to pypi. Closing this for now - feel free to reopen if you see additional issues.
